name: Elixir CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    MIX_ENV: test

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        name: Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
        strategy:
            matrix:
                otp: ["28.4.1"]
                elixir: ["1.19.5"]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Elixir
              uses: ./.github/actions/setup-elixir
              with:
                  otp-version: ${{matrix.otp}}
                  elixir-version: ${{matrix.elixir}}
                  cache-prefix: elixir
                  mix-env: test

            - name: Clean to rule out incremental build as a source of flakiness
              if: github.run_attempt != '1'
              run: |
                  mix deps.clean --all
                  mix clean
              shell: sh

            - name: Compiles without warnings
              run: mix compile --warnings-as-errors

            - name: Check formatting
              run: mix format --check-formatted

            - name: Run Credo
              run: mix credo

            - name: Run tests
              run: mix test
